"""Game-wide constants and configuration values."""

# Movement
PLAYER_MOVE_SPEED = 75  # pixels per second
PLAYER_COLLISION_WIDTH = 8
PLAYER_COLLISION_HEIGHT = 4
PLAYER_COLLISION_OFFSET_X = 4
PLAYER_COLLISION_OFFSET_Y = 8

# Timing
LOADING_SCREEN_DURATION = 0.6
DOOR_LOCKED_MESSAGE_DURATION = 2.0
CAMERA_ZOOM_TRANSITION_SPEED = 1.2
PLAYER_DAMAGE_COOLDOWN = 0.5

# Camera & Rendering
DEFAULT_CAMERA_ZOOM = 3.0
DEFAULT_LAYER = 8
ABOVE_ZONE_LAYER = 100
PROXIMITY_DETECTION_INFLATION = 32

# Collision
PLAYER_COLLISION_SIZE = (8, 4)
PLAYER_COLLISION_OFFSET = (4, 8)

# Animation
PLAYER_DAMAGE_ANIMATION_SPEED = 5

# Map
DEFAULT_MAP_PATH = "assets/maps/Tiled_files/Dungeon1.tmx"
